id: "improved_code_refinement"
type: "improved_code_refinement"  # Must match the agent class name without "Agent"
description: "Improved agent that generates and refines code through self-reflection with token-efficient architecture"

config:
  # General configuration
  max_iterations: 3
  save_results: false
  early_stop_on_success: true
  output_dir: "results/improved_patches"
  repos_dir: "data/repositories"

  # Model generation parameters
  temperature: 0.2
  max_tokens: 4000

  # Token optimization settings
  summarizer_config:
    include_docstrings: true
    include_signatures: true
    include_imports: true

  context_manager_config:
    relevance_threshold: 0.1
    max_files: 10
    include_imports: true
    include_related_functions: true

  disclosure_config:
    max_depth: 3
    max_context_per_file: 2000

  memory_manager_config:
    max_history_items: 5
    max_memory_tokens: 1000

  # Evaluation options
  test_timeout: 1000
  enable_file_exploration: true

  # Logging and debugging
  verbose_logging: true
  save_intermediate_patches: true
