id: "patch_refinement"
type: "patch_refinement"  # Must match the agent class name without "Agent"
description: "Agent that refines Git patches for fixing GitHub issues"

config:
  # General configuration
  max_iterations: 3
  save_results: true
  early_stop_on_success: true
  output_dir: "results/patches"
  repos_dir: "data/repositories"

  # Model generation parameters
  temperature: 0.2
  max_tokens: 4000

  # Evaluation options
  test_timeout: 1000
  enable_file_exploration: true

  # Logging and debugging
  verbose_logging: true
  save_intermediate_patches: true
