id: "tree_of_thought_diagnostic"
type: "tree_of_thought_diagnostic"  # Must match the agent registry key

description: "Agent that uses a tree-of-thought approach to diagnose complex matrix dimension and operator mismatch bugs."

config:
  # Tree-of-thought specific config
  depth_limit: 3
  debug_mode: true

  # BaseAgent / reflective loop configuration
  max_iterations: 3
  save_results: true
  early_stop_on_success: true
  output_dir: "results/patches"
  repos_dir: "data/repositories"

  # Model generation parameters (if needed by your agent/model)
  temperature: 0.2
  max_tokens: 4000

  # Evaluation / environment options
  test_timeout: 1000
  enable_file_exploration: true

  # Logging and debugging
  verbose_logging: true
  save_intermediate_patches: true
