# configs/agents/tree_of_thought_patch.yaml
id: "tree_of_thought_patch"
type: "tree_of_thought_patch"
description: "Tree of Thought agent that explores multiple reasoning paths to generate optimal patches"

config:
  # ToT-specific configuration
  max_branches: 3
  max_depth: 3
  selection_strategy: "best_first"
  temperature_schedule: [0.7, 0.5, 0.3]
  early_stop_threshold: 0.8

  # General configuration
  max_iterations: 3
  save_results: true
  early_stop_on_success: true
  output_dir: "results/tot_patches"

  # Context management settings
  max_tokens: 4000
  summarizer_config:
    include_docstrings: true
    include_imports: true

  # Evaluation options
  test_timeout: 300
  
