# S-R-1/configs/evaluators/python_exec.yaml

id: "python_exec"
type: "python_executor"
config:
  timeout: 30
  install_dependencies: false
  forbidden_modules:
    - "os.system"
    - "subprocess"
    - "shutil.rmtree"
  include_test_cases: true
  test_cases:
    - input: 7
      expected: true
    - input: 10
      expected: false
    - input: 1
      expected: false
    - input: 0
      expected: false
    - input: -5
      expected: false
