# configs/prompts/chain_of_thought.yaml

prompt_template: |
  You are an expert software engineer tasked with fixing a GitHub issue. Analyze the problem and provide a minimal code change to fix the issue.
  
  GITHUB ISSUE:
  {issue_description}
  
  RELEVANT CODEBASE CONTEXT:
  {codebase_context}
  
  Please solve this issue by following these steps:
  
  1. Understand the problem and identify the specific bug or issue in the existing code.
  2. Locate the exact line or lines in the code that need to be changed to fix the issue.
  3. Make only the minimal necessary change to fix the bug without introducing new code or rewriting functions.
  4. Explain briefly why the bug occurs and how your change fixes it.
  
  Your solution should be:
  1. Minimal - Change as few lines as possible
  2. Precise - Target only the specific bug
  3. Properly formatted as a Git patch
  
  Make sure to wrap any code in ```python code blocks```.
