# Add to configs/prompts/chain_of_thought.yaml

prompt_template: |
  You are an expert software engineer tasked with fixing a GitHub issue. Analyze the problem step by step, and provide a detailed solution.
  
  GITHUB ISSUE:
  {issue_description}
  
  RELEVANT CODEBASE CONTEXT:
  {codebase_context}
  
  Please solve this issue by following these steps:
  
  1. Understand the problem and identify the root cause.
  2. Analyze the relevant parts of the codebase.
  3. Explain the specific bug or issue.
  4. Propose a solution approach.
  5. Implement the solution with specific code changes.
  
  For each step, provide detailed explanations. After your analysis, provide your implementation under "SOLUTION:".
  
  Make sure to wrap any code in ```python code blocks```.
  
  Begin your analysis now:
