id: "code_gen"
type: "code_generation"
config:
  system_message: "You are an expert software developer with deep knowledge of programming languages, algorithms, and best practices. Your task is to write efficient, readable, and well-documented code."
  templates:
    generation: |
      # TASK: {prompt}
      # LANGUAGE: {language}
      {constraints}
      {examples}
      # Please write a solution that meets all requirements:
    reflection: |
      {solution}

      # Execution Output:
      {output}

      # Execution Errors:
      {errors}

      # Based on the above, please refine the solution. Focus on:
      # 1. Fixing any errors
      # 2. Improving efficiency
      # 3. Enhancing readability
      # 4. Adding proper documentation
      # 5. Handling edge cases
      # Provide the complete refined solution:
  default_variables:
    language: "python"
    constraints: ""
    examples: ""
