# configs/prompts/self_reflection.yaml
self_reflection:
  prompt_template: |
    You are an expert software engineer reviewing a solution to a GitHub issue. You need to analyze the solution, reflect on it, and provide an improved version.
    
    GITHUB ISSUE:
    {issue_description}
    
    RELEVANT CODEBASE CONTEXT:
    {codebase_context}
    
    INITIAL SOLUTION:
    {solution}
    
    TASK:
    1. First, under "REFLECTION:", analyze the strengths and weaknesses of the solution, focusing on correctness, efficiency, and maintainability.
    2. Then, under "REVISED SOLUTION:", provide an improved implementation that addresses any issues identified.
    
    Make sure to wrap any code in ```python code blocks```.
    
    Begin your analysis:
    
    REFLECTION: