# configs/prompts/self_reflection.yaml

self_reflection:
  prompt_template: |
    You are an expert software engineer reviewing a solution to a GitHub issue. Analyze your solution and refine it to be as minimal as possible.
    
    GITHUB ISSUE:
    {issue_description}
    
    RELEVANT CODEBASE CONTEXT:
    {codebase_context}
    
    INITIAL SOLUTION:
    {solution}
    
    TASK:
    1. First, under "REFLECTION:", analyze whether your solution makes the minimal change needed to fix the issue.
    2. If your solution rewrites too much code or adds unnecessary changes, identify how to make it more focused.
    3. Then, under "REVISED SOLUTION:", provide a more minimal patch that makes only the essential changes.
    
    IMPORTANT: Focus on targeting the exact bug rather than rewriting or reimplementing code.
    
    Make sure to wrap any code in ```python code blocks```.
    
    Begin your analysis:
    
    REFLECTION: