id: "swe_bench_prompt"
type: "swe_bench_prompt"
config:
  system_message: "You are an expert software developer tasked with fixing GitHub issues. You understand how to read issue descriptions, identify the underlying problems, and create patches to fix them. Follow best software engineering practices and ensure your patches are minimal and focused on solving the specific issue."
  templates:
    generation: |
      # GitHub Issue: {issue_id}

      {problem_statement}

      {repository_context}

      # Repository Information
      Repository: {repo}
      Base commit: {base_commit}

      # Task
      Your task is to create a patch that fixes this issue. The patch should be in the format of a git diff.
      Focus on creating a minimal change that addresses the issue while maintaining the code's integrity.

      Please provide a patch in git diff format.

    reflection: |
      # GitHub Issue: {issue_id}

      {problem_statement}

      # Your Previous Solution
      {solution}

      # Test Results
      {output}

      # Errors
      {errors}

      # Continuity Context
      {continuity}

      # Task
      Based on the test results above, please refine your solution. The patch should be in the format of a git diff.
      Focus on creating a minimal change that addresses the issue while maintaining the code's integrity.
      Make sure your solution passes all the required tests.

      Please provide your refined patch in git diff format.
      
    tot_reasoning: |
      # GitHub Issue: {issue_id}

      {original_prompt}

      # Repository Information
      Repository: {repo}
      Base commit: {base_commit}

      # Tree of Thought Reasoning (Depth {depth})
      You are exploring different reasoning paths to solve this problem.
      Focus on: {strategy}

      # Previous Reasoning
      {parent_reasoning}

      # Instructions
      1. Analyze the problem and previous reasoning carefully
      2. Think step-by-step about the best approach
      3. Consider potential solutions and their implications
      4. Develop a specific patch to solve the issue
      5. Output your reasoning and a complete git patch in standard diff format

      Please provide your complete reasoning and patch.
  default_variables:
    issue_id: "unknown"
    repo: "unknown"
    base_commit: "unknown"
    continuity: ""
    repository_context: ""
