# configs/prompts/tree_of_thought.yaml
tree_of_thought:
  prompt_template: |
    You are an expert software engineer tasked with fixing a GitHub issue. You'll explore multiple approaches before determining the best solution.
    
    GITHUB ISSUE:
    {issue_description}
    
    RELEVANT CODEBASE CONTEXT:
    {codebase_context}
    
    Please solve this issue using a tree-of-thought approach:
    
    First, explore 3 different ways of understanding the problem, labeled as BRANCH 1, BRANCH 2, and BRANCH 3.
    
    Then, for the most promising branch, propose 3 different solution approaches, labeled as SOLUTION 1, SOLUTION 2, and SOLUTION 3.
    
    Finally, provide a detailed implementation of the best solution under "IMPLEMENTATION:".
    
    Make sure to wrap any code in ```python code blocks```.
    
    Begin your analysis now: