# S-R-1/configs/models/qwen_coder.yaml

id: "qwen_coder"
type: "huggingface"
config:
  model_name: "Qwen/Qwen2.5-Coder-32B-Instruct"
  device_map: "auto"
  use_fp16: true
  use_8bit: false  # For H100, we can use native float16 without 8-bit quantization
  max_length: 4096  # H100 has enough memory for longer sequences
  temperature: 0.2
  top_p: 0.9
  repetition_penalty: 1.1
