# S-R-1/configs/models/qwq_preview.yaml

id: "qwq_preview"
type: "huggingface"
config:
  model_name: "Qwen/QwQ-32B-Preview"
  device_map: "auto"
  use_fp16: true
  use_8bit: false
  max_length: 4096
  temperature: 0.2
  top_p: 0.9
  repetition_penalty: 1.1
