# src/config/default_config.yaml
# Default configuration for the AI system

# System-wide settings
system:
  name: "AI Self-Reflection System"
  version: "0.1.0"
  description: "System for generating and refining solutions through self-reflection"

# Logging settings
logging:
  level: "INFO"
  console: true
  file: true
  log_dir: "logs"
  max_file_size_mb: 10
  max_backup_count: 5

# Experiment settings
experiment:
  save_results: true
  output_dir: "data/results"
  metrics_dir: "data/metrics"

# Default agent settings
agent:
  type: "code_refinement"
  max_iterations: 3
  early_stop_on_success: true

# Default model settings
model:
  type: "huggingface"
  device_map: "auto"
  use_fp16: true
  additional_tokens: 100
  max_length: 2048

# Default prompt settings
prompt:
  type: "code_generation"
  system_message: "You are a helpful AI assistant focused on coding tasks."

# Default evaluator settings
evaluator:
  type: "python_executor"
  timeout: 30
  include_test_cases: true