id: "swe_bench_verified"
type: "swe_bench"
config:
  dataset_name: "princeton-nlp/SWE-bench_Verified"
  retrieval_type: "standard"
  file_path: "data/datasets/swe_bench_verified.json"
  swe_bench_path: "data/datasets"
  repos_dir: "data/repositories"
  cache_dir: "data/datasets"
  auto_load: true
  lazy_loading: true
