id: "swe_bench_lite"
type: "swe_bench"
config:
  dataset_name: "princeton-nlp/SWE-bench_Lite"
  retrieval_type: "standard"
  file_path: "data/datasets/swe_bench_lite.json"
  repos_dir: "data/repositories"
  cache_dir: "data/datasets"
  auto_load: true
  lazy_loading: true
